### ISSUE TITLE
マウスを押したのと別の鍵盤、あるいはその他の領域で離したときに音がなり続けるのは意図した挙動か？

### ISSUE THREAD

**Issue by yumetodo** [comorebi-notes/web_piano#1]
WebAudioAPI の練習という観点からはずれてしまう報告ですが、気になったので一応。

https://github.com/comorebi-notes/web_piano/blob/2c1b03ae4a0692191c5a52da565baa6658d4726e/src/components/Key.jsx#L41

がおそらく該当だと思うのですが(React書いたことない)、マウスを押したのと別の鍵盤、あるいはその他の領域で離したときに音がなり続ける挙動を示します。

これは意図した挙動でしょうか？

**Comment by comorebi-notes** [comment]
既知のバグだったんですが、以下の記事を参考に修正しました。
https://stackoverflow.com/questions/53863191/why-is-mouseup-event-not-firing-when-releasing-outside-div-in-this-react-code-u
